name: release

on:
  push:
    branches:
    - 'release-*'

jobs:

  #build-osx:
  #  name: Macos build
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: build
  #      run: make ./p/

  #build-windows:
  #  name: Windows build
  #  runs-on: windows-latest
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      name: [vs2019_static, clang_cl]
  #      include:
  #        - name: vs2019_static
  #          compiler: cl
  #          meson_options: --default-library=static -Dstatic_runtime=true
  #        - name: clang_cl
  #          compiler: clang-cl
  #          meson_options: --default-library=shared
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-python@v2
  #    - name: install dependencies
  #      shell: pwsh
  #      run: |
  #        python -m pip install --upgrade pip
  #        pip install meson ninja
  #    - name: build with meson + ninja
  #      shell: pwsh
  #      run: |
  #        .github\vsdevenv.ps1
  #        meson --buildtype=release --prefix=$PWD\radare2-install build ${{ matrix.meson_options }}
  #        ninja -C build

  build-deb:
    name: build deb package for ${{ matrix.name }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        name: [debian-buster, ubuntu-1804]
        include:
          - name: debian-buster
            container: debian:buster
          - name: ubuntu-1804
            container: ubuntu:18.04
    steps:
      - uses: actions/checkout@v2
      - name: extract r2 version
        shell: bash
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/} | sed 's/release-//')"
        id: radare2
      - name: install requirements
        run: |
          apt-get update -qq > /dev/null
          apt-get install --yes sudo wget pkg-config build-essential libuv1-dev libssl-dev libc6 -qq > /dev/null
      - name: install radare2 and radare2-dev
        run: |
          export VERSION=${{ steps.radare2.outputs.version }}
          export DISTRIB=${{ matrix.name }}
          export GH_URL="https://github.com/radareorg/radare2/releases/download/$VERSION"
          wget --quiet -c "$GH_URL/radare2-""$DISTRIB""_""$VERSION""_amd64.deb"
          wget --quiet -c "$GH_URL/radare2-dev-""$DISTRIB""_""$VERSION""_amd64.deb"
          sudo dpkg -i *.deb
          rm -rf *.deb || sleep 0
      - name: build 
        run: |
          make -C p/dist/debian
          mv p/dist/debian/*.deb p/dist/debian/r2dec-${{ matrix.name }}_${{ steps.radare2.outputs.version }}_amd64.deb
      - name: upload .deb file
        uses: actions/upload-artifact@v2
        with:
          name: r2dec-${{ matrix.name }}-${{ steps.radare2.outputs.version }}-deb
          path: p/dist/debian/r2dec-${{ matrix.name }}_${{ steps.radare2.outputs.version }}_amd64.deb

  create-release:
    runs-on: ubuntu-latest
    needs: [build-deb]
    steps:
      - uses: actions/checkout@v2
      - name: extract r2 version
        shell: bash
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/} | sed 's/release-//')"
        id: radare2

      - uses: actions/download-artifact@v2
      - name: display structure of downloaded files
        run: ls -R

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.radare2.outputs.version }}
          release_name: Release ${{ steps.radare2.outputs.version }}
          draft: false
          prerelease: false

      - name: upload debian:buster package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./r2dec-debian-buster-${{ steps.radare2.outputs.version }}-deb/r2dec-debian-buster_${{ steps.radare2.outputs.version }}_amd64.deb
          asset_name: r2dec-debian-buster_${{ steps.radare2.outputs.version }}_amd64.deb
          asset_content_type: application/zip

      - name: upload ubuntu:18.04 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./r2dec-ubuntu-1804-${{ steps.radare2.outputs.version }}-deb/r2dec-ubuntu-1804_${{ steps.radare2.outputs.version }}_amd64.deb
          asset_name: r2dec-ubuntu-1804_${{ steps.radare2.outputs.version }}_amd64.deb
          asset_content_type: application/zip